### ISSUE TITLE
Exercise: Create repository and upload by hand

### ISSUE THREAD

**Issue by MichaelMadsen** [praqma-training/artifactory-kata#1]
Prerequisites: none

User creates 3 local repositories: 2 generic gradle and 1 custom gradle.
Then 2 virtual repositories: 1 spanning the 2 generic, 1 that spans over a generic and a custom.

Learning goals:
How to create repositories through UI
How to upload a file by hand
Differences between generic and custom layout
Virtual repository can only do magic (create gradle dependency declaration) when it spans the same type of repositories

**Comment by sofusalbertsen** [comment]
This one needs to be reworked to fit the new structure.

**Comment by sofusalbertsen** [comment]
And adding Native Browser

**Comment by sofusalbertsen** [comment]
Delete custom layout and virtual layout.
Make rest
