### ISSUE TITLE
Exercise: Gradle dependency download

### ISSUE THREAD

**Issue by sofusalbertsen** [praqma-training/artifactory-kata#11]
* Test that gradle exists
* Add the artifactory plugin
* Make sure the artifacts are uploaded
* Download and check the artifacts

**Comment by sofusalbertsen** [comment]
Also: Repo type Gradle (dependency declaration)

**Comment by MichaelMadsen** [comment]
@sofusalbertsen First draft is ready for sanity check in the `gradle_intro` folder

**Comment by sofusalbertsen** [comment]
Done, Nice work :)
