### ISSUE TITLE
Exercise: Gradle remote setup + multi repo dependency in gradle

### ISSUE THREAD

**Issue by sofusalbertsen** [praqma-training/artifactory-kata#12]
* How to add the remote repo in artifactory
* add it to Gradle
* Download an artifact via gradle

**Comment by sofusalbertsen** [comment]
This is without the artifactory plugin avaliable

**Comment by MichaelMadsen** [comment]
@sofusalbertsen First draft is ready for sanity check in the `gradle_remote_and_artifactory_plugin` folder
