### ISSUE TITLE
 Exercise: Gradle Builds

### ISSUE THREAD

**Issue by sofusalbertsen** [praqma-training/artifactory-kata#14]

**Comment by sofusalbertsen** [comment]
Capturing the build number and env info to make a build entity in artifactory

**Comment by MichaelMadsen** [comment]
TODO: Rework "promote_curl" and incorporate in gradle build exercise

**Comment by MichaelMadsen** [comment]
@bicschneider There are 2 things I could use help with today, if you have the time.

1. Figure out why `setup.sh` is not creating the 2 files I want it to. Hopefully it is just some syntax issues. It's supposed to fill out `build.gradle` and `gradle.properties`.
2. Give feedback on the exercise so far. It still needs to incorporate promotes through curl in the end of the exercise, but apart from that the structure is done.

**Comment by MichaelMadsen** [comment]
Maybe we should take inspiration from the gradle katas and just have the files in the shared directory, instead of piping them in through setup.sh. Like this one:
`cat ../../.shared/pre-existing/custom-task-type.gradle > build.gradle`

**Comment by MichaelMadsen** [comment]
Step 1 in the comment above has been solved - it stopped execution due to `set -e` in the util.sh script, which we have removed for now. I know that it's not the ideal solution, but it works and that's what we need right now.
So now we just need feedback for the exercise itself.

**Comment by MichaelMadsen** [comment]
Curl publish done, exercise finalised. Now just needs sanity check.

**Comment by bicschneider** [comment]
I find the intro `Creating Artifactory builds with Gradle` confusing.. I perceive it as a mixture of description, preparation, exercise .. It is not clear..  Missing structure

**Comment by bicschneider** [comment]
the exercises works well ..
